import { IAuditSolaireSimulation, MonthlyConsumptionData, MonthlyPVProductionData, MonthlyEconomicData, AnnualEconomicData } from '@shared/interfaces/audit-solaire.interface';
export interface MonthlyConsumptionDto extends MonthlyConsumptionData { }
export interface MonthlyPVProductionDto extends MonthlyPVProductionData { }
export interface MonthlyEconomicDto extends MonthlyEconomicData { }
export interface AnnualEconomicDto extends AnnualEconomicData { }

export interface AuditSolaireResponseDto extends Omit<IAuditSolaireSimulation, 'createdAt' | 'updatedAt'> { createdAt: Date; updatedAt: Date; }

export function toAuditSolaireResponseDto(simulation: IAuditSolaireSimulation): AuditSolaireResponseDto {
  return {
    id: simulation.id,
    address: simulation.address ,
    fullName: simulation.fullName ,
    companyName: simulation.companyName ,
    email: simulation.email ,
    phoneNumber: simulation.phoneNumber ,
    latitude: simulation.latitude,
    longitude: simulation.longitude,
    buildingType: simulation.buildingType,
    climateZone: simulation.climateZone,
    measuredAmount: simulation.measuredAmount,
    referenceMonth: simulation.referenceMonth,
    baseConsumption: simulation.baseConsumption ,
    monthlyConsumptions: simulation.monthlyConsumptions?.map(mc => ({
      month: mc.month,
      rawConsumption: mc.rawConsumption,
      estimatedConsumption: mc.estimatedConsumption,
      climaticCoefficient: mc.climaticCoefficient,
      buildingCoefficient: mc.buildingCoefficient,
      effectiveCoefficient: mc.effectiveCoefficient,
    })) || [],
    annualConsumption: simulation.annualConsumption,
    annualProductible: simulation.annualProductible,
    installedPower: simulation.installedPower,
    annualProducible: simulation.annualProducible,
    expectedProduction: simulation.expectedProduction,
    energyCoverageRate: simulation.energyCoverageRate,
    monthlyPVProductions: simulation.monthlyPVProductions?.map(mp => ({
      month: mp.month,
      rawConsumption: mp.rawConsumption,
      pvProduction: mp.pvProduction,
      netConsumption: mp.netConsumption,
      credit: mp.credit,
    })) || [],
    installationCost: simulation.installationCost,
    annualOpex: simulation.annualOpex,
    annualSavings: simulation.annualSavings,
    totalSavings25Years: simulation.totalSavings25Years,
    simplePaybackYears: simulation.simplePaybackYears,
    discountedPaybackYears: simulation.discountedPaybackYears,
    roi25Years: simulation.roi25Years,
    npv: simulation.npv,
    irr: simulation.irr,
    annualCo2Avoided: simulation.annualCo2Avoided,
    totalCo2Avoided25Years: simulation.totalCo2Avoided25Years,
    monthlyEconomics: simulation.monthlyEconomics?.map(me => ({
      month: me.month,
      rawConsumption: me.rawConsumption,
      billedConsumption: me.billedConsumption,
      appliedTariffRate: me.appliedTariffRate,
      billWithoutPV: me.billWithoutPV,
      billWithPV: me.billWithPV,
      monthlySavings: me.monthlySavings,
    })) || [],
    annualEconomics: simulation.annualEconomics?.map(ae => ({
      year: ae.year,
      annualRawConsumption: ae.annualRawConsumption,
      annualBilledConsumption: ae.annualBilledConsumption,
      annualBillWithoutPV: ae.annualBillWithoutPV,
      annualBillWithPV: ae.annualBillWithPV,
      annualSavings: ae.annualSavings,
      averageAvoidedTariff: ae.averageAvoidedTariff,
      capex: ae.capex,
      opex: ae.opex,
      netGain: ae.netGain,
      cumulativeCashFlow: ae.cumulativeCashFlow,
      cumulativeCashFlowDiscounted: ae.cumulativeCashFlowDiscounted,
      cumulativeNetGain: ae.cumulativeNetGain,
      cumulativeNetGainDiscounted: ae.cumulativeNetGainDiscounted,
    })) || [],
    systemSize_kWp: simulation.systemSize_kWp,
    coverage: simulation.coverage,
    annualBillWithoutPV: simulation.annualBillWithoutPV,
    annualBillWithPV: simulation.annualBillWithPV,
    averageAnnualSavings: simulation.averageAnnualSavings,
    paybackMonths: simulation.paybackMonths,
    createdAt: simulation.createdAt,
    updatedAt: simulation.updatedAt,
  };
}
